import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [message, setMessage] = useState("");

  const startTaskLoop = async () => {
    try {
      const response = await fetch("/api/tasks");
      const data = await response.json();
      setMessage(data.message);
    } catch (error) {
      console.error(error);
      setMessage("An error occurred while starting the task loop");
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <h1>Task Loop</h1>
        <button onClick={startTaskLoop}>Start Task Loop</button>
        {message && <p>{message}</p>}
      </main>
    </>
  );
}
