import { Agent } from '@/components/Agent/Agent';
import { Sidebar } from '@/components/Sidebar/Sidebar';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>BabyAGI-UI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen w-screen flex-col text-sm text-white dark:text-white">
        <div className="flex h-full w-full pt-12 sm:pt-0">
          <div>
            <Sidebar />
          </div>
          <Agent />
        </div>
      </main>
    </>
  );
}
